fix- TypeError: Loop.__init__() missing 1 required positional argument: 'overlap'
Signed-off-by: Lumouille <144063653+Lumabots@users.noreply.github.com>